services:
  - type: web
    name: kynohealth-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: streamlit run app.py
    envVars:
      - key: GEMINI_API_KEY
        value: your-api-key-here
